version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: ticketing-db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticketing
      TZ: Asia/Seoul

  redis:
    image: redis:latest
    container_name: ticketing-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: ticketing-prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: ticketing-grafana
    ports:
      - "3000:3000"
