version: '3.9'

services:
  ticketing-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticketing
      TZ: Asia/Seoul

  ticketing-redis:
    image: redis:latest
    ports:
      - "6379:6379"