server:
  port: 8080

spring:
  application:
    name: ticket911

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketing?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

redis:
  host: localhost
  port: 6379

jwt:
  token:
    access:
      second: 60
      minute: 60
      hour: 12

  secret:
    key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
