version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ticket911-app
    ports:
      - "8080:8080"
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    container_name: ticket911-prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus-prod.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: ticket911-grafana
    ports:
      - "3000:3000"
